import { Vehicle, CargoOrder, MaintenanceJob, SystemLog } from './types';

// Coordinates of major transport hubs in Saudi Arabia
export const SAUDI_TRANSPORT_HUBS = [
  { city: 'Riyadh', name: 'Riyadh HQ Transport Center', lat: 24.7136, lng: 46.6753, arName: 'مركز نقل الرياض الرئيسي' },
  { city: 'Jeddah', name: 'Jeddah Seaport Container Terminal', lat: 21.5433, lng: 39.1728, arName: 'محطة حاويات ميناء جدة' },
  { city: 'Dammam', name: 'King Abdulaziz Port Dammam Hub', lat: 26.4207, lng: 50.0888, arName: 'ميناء الملك عبد العزيز بالدمام' },
  { city: 'Mecca', name: 'Mecca Pilgrimage Transport Station', lat: 21.3891, lng: 39.8579, arName: 'محطة نقل الحجاج بمكة المكرمة' },
  { city: 'Medina', name: 'Medina Regional Freight Terminal', lat: 24.4672, lng: 39.6111, arName: 'محطة شحن منطقة المدينة المنورة' },
  { city: 'Jubail', name: 'Jubail Industrial Transport Park', lat: 27.0112, lng: 49.6583, arName: 'منطقة الجبيل الصناعية' },
  { city: 'Yanbu', name: 'Yanbu Industrial Harbor Supply Hub', lat: 24.0891, lng: 38.0637, arName: 'مركز إمدادات ينبع الصناعي' }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'QMF-101',
    plateNumber: 'أ ب ج ١ ٢ ٣ ٤',
    type: 'Water Tanker',
    driverName: 'Mohammed Al-Sharif',
    driverPhone: '+966 50 123 4567',
    status: 'In Transit',
    location: { lat: 24.6300, lng: 46.7100, city: 'Riyadh' },
    capacity: '19,000 Liters',
    fuelLevel: 78,
    lastMaintenance: '2026-05-10'
  },
  {
    id: 'QMF-102',
    plateNumber: 'د ر س ٥ ٦ ٧ ٨',
    type: 'Heavy Trailer',
    driverName: 'Yaseen Al-Habshi',
    driverPhone: '+966 55 987 6543',
    status: 'Available',
    location: { lat: 21.5433, lng: 39.1728, city: 'Jeddah' },
    capacity: '25 Tons',
    fuelLevel: 92,
    lastMaintenance: '2026-06-01'
  },
  {
    id: 'QMF-103',
    plateNumber: 'ط ي ر ٩ ٠ ٢ ٤',
    type: 'Flatbed Truck',
    driverName: 'Osama Ibrahim',
    driverPhone: '+966 54 333 8811',
    status: 'In Transit',
    location: { lat: 26.2000, lng: 50.1000, city: 'Dammam' },
    capacity: '15 Tons',
    fuelLevel: 45,
    lastMaintenance: '2026-04-18'
  },
  {
    id: 'QMF-104',
    plateNumber: 'ع س ل ٣ ٣ ٩ ٩',
    type: 'Passenger Bus',
    driverName: 'Abdulrahman Qahtani',
    driverPhone: '+966 56 112 0044',
    status: 'Available',
    location: { lat: 21.3891, lng: 39.8579, city: 'Mecca' },
    capacity: '50 Seats',
    fuelLevel: 85,
    lastMaintenance: '2026-05-28'
  },
  {
    id: 'QMF-105',
    plateNumber: 'م ن ك ٧ ٧ ٥ ٥',
    type: 'Excavator',
    driverName: 'Khalid Masoud',
    driverPhone: '+966 53 777 5522',
    status: 'Maintenance',
    location: { lat: 27.0112, lng: 49.6583, city: 'Jubail' },
    capacity: 'Heavy Duty Category IV',
    fuelLevel: 15,
    lastMaintenance: '2026-06-13'
  },
  {
    id: 'QMF-106',
    plateNumber: 'هـ ب ط ٢ ٢ ٤ ٤',
    type: 'Water Tanker',
    driverName: 'Saeed Al-Zahrani',
    driverPhone: '+966 59 444 3322',
    status: 'Off Duty',
    location: { lat: 24.4672, lng: 39.6111, city: 'Medina' },
    capacity: '19,000 Liters',
    fuelLevel: 100,
    lastMaintenance: '2026-06-05'
  }
];

export const INITIAL_CARGO_ORDERS: CargoOrder[] = [
  {
    id: 'ORD-9021',
    clientName: 'Al-Khobar Pilgrimage Delegation',
    clientPhone: '+966 50 111 2222',
    vehicleType: 'Mercedes Tourismo Bus',
    origin: 'King Abdulaziz Airport Jeddah',
    destination: 'Makkah Clock Tower Hotel',
    cargoType: 'Umrah Pilgrims & Luggage',
    weightOrVolume: '45 Passengers',
    status: 'In Transit',
    assignedVehicleId: 'QMF-103',
    estimatedPrice: 2200,
    createdAt: '2026-06-14T08:30:00Z',
    notes: 'Airport terminal pickup with greeting sign.'
  },
  {
    id: 'ORD-9022',
    clientName: 'Al-Noor Family Delegation',
    clientPhone: '+966 55 333 4444',
    vehicleType: 'GMC Yukon XL (VIP)',
    origin: 'Jeddah Hotel',
    destination: 'Makkah Al-Mukarramah',
    cargoType: 'Family VIP Transport',
    weightOrVolume: '6 Passengers',
    status: 'Pending',
    estimatedPrice: 650,
    createdAt: '2026-06-14T11:15:00Z',
    notes: 'Child seats and ample trunk room requested.'
  },
  {
    id: 'ORD-9023',
    clientName: 'Hajj & Umrah Tourism Corp',
    clientPhone: '+966 56 777 8888',
    vehicleType: 'Passenger Bus',
    origin: 'King Abdulaziz Airport Jeddah',
    destination: 'Medina Al Mizan Hotel',
    cargoType: 'Pilgrimage Passengers',
    weightOrVolume: '45 Passengers',
    status: 'Completed',
    assignedVehicleId: 'QMF-104',
    estimatedPrice: 3200,
    createdAt: '2026-06-13T09:00:00Z',
    notes: 'Mecca detour verified, luxury class ride provided.'
  },
  {
    id: 'ORD-9024',
    clientName: 'Al-Haramain Group Tour',
    clientPhone: '+966 53 444 5555',
    vehicleType: 'Toyota HiAce Minivan',
    origin: 'Madinah Central Area',
    destination: 'Historical Ziyarat Landmarks',
    cargoType: 'Guided Ziyarat Tour',
    weightOrVolume: '12 Passengers',
    status: 'Assigned',
    assignedVehicleId: 'QMF-102',
    estimatedPrice: 950,
    createdAt: '2026-06-14T14:00:00Z',
    notes: 'Full guided tour for Quba, Uhud, and Qiblatayn.'
  }
];

export const INITIAL_MAINTENANCE_JOBS: MaintenanceJob[] = [
  {
    id: 'MNT-401',
    vehicleId: 'QMF-105',
    plateNumber: 'م ن ك ٧ ٧ ٥ ٥',
    vehicleType: 'Mercedes Tourismo Bus',
    issue: 'High-speed A/C maintenance & cabin filter replacement',
    cost: 1400,
    status: 'In Progress',
    date: '2026-06-13'
  },
  {
    id: 'MNT-402',
    vehicleId: 'QMF-101',
    plateNumber: 'أ ب ج ١ ٢ ٣ ٤',
    vehicleType: 'Toyota Coaster',
    issue: 'Brake inspection and tire rotation',
    cost: 850,
    status: 'Resolved',
    date: '2026-06-10'
  }
];

export const INITIAL_LOGS: SystemLog[] = [
  {
    id: 'LOG-001',
    timestamp: '2026-06-14T13:45:00Z',
    type: 'success',
    actor: 'Trip Coordinator',
    message: 'Route confirmed and driver assigned for Jeddah-Makkah transfer.'
  },
  {
    id: 'LOG-002',
    timestamp: '2026-06-14T14:10:00Z',
    type: 'info',
    actor: 'Customer Support Lead',
    message: 'Vehicle QMF-102 status set to Available at Jeddah Station.'
  },
  {
    id: 'LOG-003',
    timestamp: '2026-06-14T14:32:00Z',
    type: 'info',
    actor: 'Maintenance Hub',
    message: 'Vehicle QMF-105 completed scheduled A/C maintenance successfully.'
  }
];

// ARABIC & ENGLISH TRANSLATION RESOURCE
export const TRANSLATIONS = {
  en: {
    brandName: 'Qawafil Al Majd Al Misaliya',
    brandSub: 'Qawafil Al Majd Al Misaliya - Transport Services',
    dashboard: 'Dashboard',
    fleetTracking: 'Live Fleet Map',
    orderBooking: 'Pilgrim & Vehicle Bookings',
    fleetRoster: 'Fleet & Bus Roster',
    maintenance: 'Maintenance Board',
    systemLogs: 'System Audit Logs',
    activeShipments: 'Active Trips',
    availableFleets: 'Standby Vehicles',
    criticalAlerts: 'Svc Alerts',
    completedTrips: 'Trips Completed',
    newCargoBooking: 'New Trip Booking',
    addVehicle: 'Register New Vehicle',
    trackShipment: 'Trip Route Monitor',
    plateText: 'Plate Number',
    driver: 'Assignee / Driver',
    capacity: 'Passenger Capacity',
    fuel: 'Fuel Indicator',
    status: 'Status',
    actions: 'Control Panel',
    arabicPlate: 'Arabic Plate Letters/Numbers',
    chooseType: 'Select Vehicle Class',
    origin: 'Pickup Location',
    destination: 'Destination / Hotel',
    weightVol: 'Luggage Capacity',
    estimatedPrice: 'Est. Trip Rate',
    priceCurrency: 'SAR (Saudi Riyal)',
    searchLabel: 'Search booking, vehicle, or driver name...',
    allCities: 'Saudi Holy Sites & City Hubs',
    chatPlaceholder: 'Message active drivers on the route...',
    sentMsg: 'Operations Office',
    driverStatus: 'Driver Alert Notification',
    createOrderSuccess: 'Trip booking registered in database!',
    createVehicleSuccess: 'Vehicle asset added to database!',
    statusPending: 'Pending Confirmation',
    statusAssigned: 'Driver Assigned',
    statusTransit: 'En Route',
    statusCompleted: 'Arrived Safe',
    statusCancelled: 'Cancelled Trip',
    langToggle: 'بالعربية',
    saveBtn: 'Save & Commit',
    cancelBtn: 'Close Dialog',
    statsChartTitle: 'Revenue Trend per Destination (SAR)',
    activeDutyPct: 'Fleet Mobility Rate',
    driverNamePlaceholder: 'e.g. Salim Al Hosni',
    driverPhonePlaceholder: 'e.g. +966 50 123 4567',
    capacityPlaceholder: 'e.g. 45 Passengers / Luggage',
  },
  ar: {
    brandName: 'قوافل المجد المثالية',
    brandSub: 'قوافل المجد المثالية لنقل الحجاج والمعتمرين',
    dashboard: 'لوحة التحكم والمتابعة',
    fleetTracking: 'الخريطة المباشرة والمسارات',
    orderBooking: 'حجوزات رحلات المعتمرين والزوار',
    fleetRoster: 'أسطول الحافلات والمركبات الفاخرة',
    maintenance: 'الصيانة والورش الفنية',
    systemLogs: 'سجلات العمليات والنظام',
    activeShipments: 'الرحلات النشطة',
    availableFleets: 'المركبات المتاحة',
    criticalAlerts: 'تنبيهات الصيانة',
    completedTrips: 'الرحلات المكتملة',
    newCargoBooking: 'تسجيل حجز رحلة جديدة',
    addVehicle: 'تسجيل مركبة في الأسطول',
    trackShipment: 'مسار تتبع الرحلة المباشر',
    plateText: 'رقم اللوحة',
    driver: 'السائق المعين',
    capacity: 'السعة وسعة الركاب',
    fuel: 'مؤشر الوقود',
    status: 'الحالة التشغيلية',
    actions: 'التحكم والتوجيه',
    arabicPlate: 'حروف وأرقام اللوحة العربية',
    chooseType: 'اختر تصنيف المركبة/الحافلة',
    origin: 'موقع الاستلام (نقطة الانطلاق)',
    destination: 'موقع التسليم (الفندق/الوجهة)',
    weightVol: 'سعة الأمتعة / الحقائب',
    estimatedPrice: 'التكلفة التقديرية للرحلة',
    priceCurrency: 'ريال سعودي',
    searchLabel: 'ابحث عن حجز، رقم لوحة، أو اسم سائق...',
    allCities: 'المشاعر المقدسة ومراكز النقل بالمملكة',
    chatPlaceholder: 'أرسل تنبيهاً أو رسالة إلى سائقي الرحلات النشطة...',
    sentMsg: 'مكتب العمليات والتنسيق',
    driverStatus: 'تنبيه السائق المباشر',
    createOrderSuccess: 'تم تسجيل حجز الرحلة بنجاح!',
    createVehicleSuccess: 'تمت إضافة المركبة لأسطول النقل بنجاح!',
    statusPending: 'قيد التأكيد',
    statusAssigned: 'تم تعيين السائق',
    statusTransit: 'في الطريق',
    statusCompleted: 'وصلت الرحلة بأمان',
    statusCancelled: 'رحلة ملغاة',
    langToggle: 'English UI',
    saveBtn: 'حفظ وتأكيد البيانات',
    cancelBtn: 'إغلاق النافذة',
    statsChartTitle: 'توزيع الإيرادات حسب المدن ومسارات الزيارات (بالريال السعودي)',
    activeDutyPct: 'نسبة جاهزية الأسطول',
    driverNamePlaceholder: 'مثال: يوسف الشمري',
    driverPhonePlaceholder: 'مثال: 966501234567+',
    capacityPlaceholder: 'مثال: 45 راكب أو حافلة VIP',
  }
};
